### ISSUE TITLE
No longer works now that Mendeley encrypts its database

### ISSUE THREAD

**Issue by bwiernik** [rdiaz02/Adios_Mendeley#4]
Mendeley has started to encrypt the local sqlite database (shortly after Zotero released a native tool to import Mendeley databases), so this workflow doesn't work with Mendeley version 1.19 and later.

**Comment by rdiaz02** [comment]
Thanks for pointing it out (I wasn't aware of it).

Well, those are bad news for Mendeley users, I guess. And that is another good reason to say goodbye to Mendeley.  Of course, my code will be useless in this case.

**Comment by bwiernik** [comment]
Users who download version 1.18 could still use it. (Zotero also recently added tools to import directly from Mendeley 1.18 and earlier databases).

Thank you for your code, though! I've pointed many people to it over the years.

**Comment by rdiaz02** [comment]
Thanks for the update about using v. 1.18 (and for your comments about the code :-) ---though I'd use Zotero's importer now :-).

**Comment by williamgunn** [comment]
Hi @rdiaz02 @bwiernik , not sure if you're still maintaining or using this, but we are sorry for breaking your script! We would like to officially support local database access in a way that will keep working as we make changes to the db & we're currently collecting use cases and setting up one-on-ones with the dev team, so if you'd like to give the Mendeley developers some feedback on what data you need to access so we can make sure to support your use case, please get in touch via email.

**Comment by rdiaz02** [comment]
I am not using this myself anymore (I used it, got what I needed, and got done with it), though other people might. What data do I need? The script used the sqlite Mendely db. If that is no longer accessible then the script won't work.

**Comment by williamgunn** [comment]
So do I understand you to be saying that if there was a local API or an
export function that produced the same information, that would have worked
just as well?

William Gunn
+1 (650) 614-1749
http://synthesis.williamgunn.org/about/

**Comment by bwiernik** [comment]
The goal of this script (and also Zotero’s analogous function) was to export ALL of the data available in a Mendeley account via the local database. If there were an API that could provide all of the data (items, folders, groups, tags, files, annotations, etc.) in an easily exportable format, that would suffice. But also just un-encrypting the database would be equally functional.

**Comment by rdiaz02** [comment]
@bwiernik is correct.

Note, though, that at least for my case (the case of this script) having to access through an API would be a major hassle relative to directly having the sqlite database (it would be necessary to call the API from R, which would probably mean through calls to the system, etc; a pain).

Regardless, I think as of today my scripts are probably not the way to go. Instead, what I think we would all like to see working for posterity would be Zotero's native import (for references see https://www.zotero.org/support/kb/mendeley_import and https://forums.zotero.org/discussion/72260/available-for-beta-testing-mendeley-import ).

**Comment by williamgunn** [comment]
We're looking into (possibly) a local API that will not only have all the
info, but also not require cloud sync and will be officially supported &
stable through whatever future db changes we make. The tradeoff is that you
would have to interface with the API instead of just using existing sqlite
drivers. Another option might be sqlite export, so existing tooling would
work, but you wouldn't be able to write back to the active db. Not sure
which would be preferred at this point, but if it's OK  I'll pass your
names on to our usability research contact & she can get in touch? I
suggest this because it would mean more coming directly from you than via
me.

William Gunn
+1 (650) 614-1749
http://synthesis.williamgunn.org/about/

On Jun 28, 2018 2:08 PM, "Brenton M. Wiernik" <notifications@github.com>
wrote:

The goal of this script (and also Zotero’s analogous function) was to
export ALL of the data available in a Mendeley account via the local
database. If there were an API that could provide all of the data (items,
folders, groups, tags, files, annotations, etc.) in an easily exportable
format, that would suffice. But also just un-encrypting the database would
be equally functional.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/rdiaz02/Adios_Mendeley/issues/4#issuecomment-401173876>,
or mute the thread

**Comment by bwiernik** [comment]
Fine by me. Thanks.

**Comment by EChesters** [comment]
Hi @bwiernik, 

Apologies for reaching out on this forum, as I could not find an email to contact you on. I am Elizabeth, one of the designers at Mendeley who would be interested in hearing your feedback, as William suggested. 

Please could you let me know what time would be best for you, at mendeley.design@elsevier.com?

Many thanks,
Elizabeth
